name: test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-latest
          - os: macos-latest

    steps:
      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version: ">=1.20.0"

      - uses: actions/checkout@v4

      - name: Build
        run: go build

      - name: Lint
        uses: golangci/golangci-lint-action@v4

      - name: Run tests
        run: go test
